# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PowerBuilding531' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PowerBuilding531
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'MaterialComponents'
  pod 'MaterialComponents/Buttons+ButtonThemer'

end
